# Generated by Django 5.2.8 on 2025-11-26 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('IN', 'Entry Scan'), ('OUT', 'Exit Scan')], max_length=5)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metro.station')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_history', to='metro.ticket')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
