# Generated by Django 5.2.8 on 2025-11-26 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0003_alter_ticket_owner_delete_scanhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footfall', to='metro.station')),
            ],
            options={
                'unique_together': {('station', 'date')},
            },
        ),
    ]
