# Generated by Django 5.2.8 on 2025-11-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0004_footfall'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetroService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=True)),
            ],
        ),
    ]
