# Generated by Django 5.2.8 on 2025-12-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0005_metroservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
